#pragma once
#include "gfx.h"

C_LINKAGE_BEGIN

// @TODO(alex): should codegen this
String os_g_key_display_string_table[143] = {
    str_lit_comp("Invalid Key"),
    str_lit_comp("Escape"),
    str_lit_comp("F1"),
    str_lit_comp("F2"),
    str_lit_comp("F3"),
    str_lit_comp("F4"),
    str_lit_comp("F5"),
    str_lit_comp("F6"),
    str_lit_comp("F7"),
    str_lit_comp("F8"),
    str_lit_comp("F9"),
    str_lit_comp("F10"),
    str_lit_comp("F11"),
    str_lit_comp("F12"),
    str_lit_comp("F13"),
    str_lit_comp("F14"),
    str_lit_comp("F15"),
    str_lit_comp("F16"),
    str_lit_comp("F17"),
    str_lit_comp("F18"),
    str_lit_comp("F19"),
    str_lit_comp("F20"),
    str_lit_comp("F21"),
    str_lit_comp("F22"),
    str_lit_comp("F23"),
    str_lit_comp("F24"),
    str_lit_comp("Tick"),
    str_lit_comp("0"),
    str_lit_comp("1"),
    str_lit_comp("2"),
    str_lit_comp("3"),
    str_lit_comp("4"),
    str_lit_comp("5"),
    str_lit_comp("6"),
    str_lit_comp("7"),
    str_lit_comp("8"),
    str_lit_comp("9"),
    str_lit_comp("Minus"),
    str_lit_comp("Equal"),
    str_lit_comp("Backspace"),
    str_lit_comp("Tab"),
    str_lit_comp("Q"),
    str_lit_comp("W"),
    str_lit_comp("E"),
    str_lit_comp("R"),
    str_lit_comp("T"),
    str_lit_comp("Y"),
    str_lit_comp("U"),
    str_lit_comp("I"),
    str_lit_comp("O"),
    str_lit_comp("P"),
    str_lit_comp("Left Bracket"),
    str_lit_comp("Right Bracket"),
    str_lit_comp("Back Slash"),
    str_lit_comp("Caps Lock"),
    str_lit_comp("A"),
    str_lit_comp("S"),
    str_lit_comp("D"),
    str_lit_comp("F"),
    str_lit_comp("G"),
    str_lit_comp("H"),
    str_lit_comp("J"),
    str_lit_comp("K"),
    str_lit_comp("L"),
    str_lit_comp("Semicolon"),
    str_lit_comp("Quote"),
    str_lit_comp("Return"),
    str_lit_comp("Shift"),
    str_lit_comp("Z"),
    str_lit_comp("X"),
    str_lit_comp("C"),
    str_lit_comp("V"),
    str_lit_comp("B"),
    str_lit_comp("N"),
    str_lit_comp("M"),
    str_lit_comp("Comma"),
    str_lit_comp("Period"),
    str_lit_comp("Slash"),
    str_lit_comp("Ctrl"),
    str_lit_comp("Alt"),
    str_lit_comp("Space"),
    str_lit_comp("Menu"),
    str_lit_comp("Scroll Lock"),
    str_lit_comp("Pause"),
    str_lit_comp("Insert"),
    str_lit_comp("Home"),
    str_lit_comp("Page Up"),
    str_lit_comp("Delete"),
    str_lit_comp("End"),
    str_lit_comp("Page Down"),
    str_lit_comp("Up"),
    str_lit_comp("Left"),
    str_lit_comp("Down"),
    str_lit_comp("Right"),
    str_lit_comp("Ex0"),
    str_lit_comp("Ex1"),
    str_lit_comp("Ex2"),
    str_lit_comp("Ex3"),
    str_lit_comp("Ex4"),
    str_lit_comp("Ex5"),
    str_lit_comp("Ex6"),
    str_lit_comp("Ex7"),
    str_lit_comp("Ex8"),
    str_lit_comp("Ex9"),
    str_lit_comp("Ex10"),
    str_lit_comp("Ex11"),
    str_lit_comp("Ex12"),
    str_lit_comp("Ex13"),
    str_lit_comp("Ex14"),
    str_lit_comp("Ex15"),
    str_lit_comp("Ex16"),
    str_lit_comp("Ex17"),
    str_lit_comp("Ex18"),
    str_lit_comp("Ex19"),
    str_lit_comp("Ex20"),
    str_lit_comp("Ex21"),
    str_lit_comp("Ex22"),
    str_lit_comp("Ex23"),
    str_lit_comp("Ex24"),
    str_lit_comp("Ex25"),
    str_lit_comp("Ex26"),
    str_lit_comp("Ex27"),
    str_lit_comp("Ex28"),
    str_lit_comp("Ex29"),
    str_lit_comp("Num Lock"),
    str_lit_comp("Numpad Slash"),
    str_lit_comp("Numpad Star"),
    str_lit_comp("Numpad Minus"),
    str_lit_comp("Numpad Plus"),
    str_lit_comp("Numpad Period"),
    str_lit_comp("Numpad 0"),
    str_lit_comp("Numpad 1"),
    str_lit_comp("Numpad 2"),
    str_lit_comp("Numpad 3"),
    str_lit_comp("Numpad 4"),
    str_lit_comp("Numpad 5"),
    str_lit_comp("Numpad 6"),
    str_lit_comp("Numpad 7"),
    str_lit_comp("Numpad 8"),
    str_lit_comp("Numpad 9"),
    str_lit_comp("Left Mouse Button"),
    str_lit_comp("Middle Mouse Button"),
    str_lit_comp("Right Mouse Button"),
};

// @TODO(alex): should codegen this
String os_g_key_cfg_string_table[143] = {
    str_lit_comp("null"),
    str_lit_comp("esc"),
    str_lit_comp("f1"),
    str_lit_comp("f2"),
    str_lit_comp("f3"),
    str_lit_comp("f4"),
    str_lit_comp("f5"),
    str_lit_comp("f6"),
    str_lit_comp("f7"),
    str_lit_comp("f8"),
    str_lit_comp("f9"),
    str_lit_comp("f10"),
    str_lit_comp("f11"),
    str_lit_comp("f12"),
    str_lit_comp("f13"),
    str_lit_comp("f14"),
    str_lit_comp("f15"),
    str_lit_comp("f16"),
    str_lit_comp("f17"),
    str_lit_comp("f18"),
    str_lit_comp("f19"),
    str_lit_comp("f20"),
    str_lit_comp("f21"),
    str_lit_comp("f22"),
    str_lit_comp("f23"),
    str_lit_comp("f24"),
    str_lit_comp("tick"),
    str_lit_comp("0"),
    str_lit_comp("1"),
    str_lit_comp("2"),
    str_lit_comp("3"),
    str_lit_comp("4"),
    str_lit_comp("5"),
    str_lit_comp("6"),
    str_lit_comp("7"),
    str_lit_comp("8"),
    str_lit_comp("9"),
    str_lit_comp("minus"),
    str_lit_comp("equal"),
    str_lit_comp("backspace"),
    str_lit_comp("tab"),
    str_lit_comp("q"),
    str_lit_comp("w"),
    str_lit_comp("e"),
    str_lit_comp("r"),
    str_lit_comp("t"),
    str_lit_comp("y"),
    str_lit_comp("u"),
    str_lit_comp("i"),
    str_lit_comp("o"),
    str_lit_comp("p"),
    str_lit_comp("left_bracket"),
    str_lit_comp("right_bracket"),
    str_lit_comp("backslash"),
    str_lit_comp("caps_lock"),
    str_lit_comp("a"),
    str_lit_comp("s"),
    str_lit_comp("d"),
    str_lit_comp("f"),
    str_lit_comp("g"),
    str_lit_comp("h"),
    str_lit_comp("j"),
    str_lit_comp("k"),
    str_lit_comp("l"),
    str_lit_comp("semicolon"),
    str_lit_comp("quote"),
    str_lit_comp("return"),
    str_lit_comp("shift"),
    str_lit_comp("z"),
    str_lit_comp("x"),
    str_lit_comp("c"),
    str_lit_comp("v"),
    str_lit_comp("b"),
    str_lit_comp("n"),
    str_lit_comp("m"),
    str_lit_comp("comma"),
    str_lit_comp("period"),
    str_lit_comp("slash"),
    str_lit_comp("ctrl"),
    str_lit_comp("alt"),
    str_lit_comp("space"),
    str_lit_comp("menu"),
    str_lit_comp("scroll_lock"),
    str_lit_comp("pause"),
    str_lit_comp("insert"),
    str_lit_comp("home"),
    str_lit_comp("page_up"),
    str_lit_comp("delete"),
    str_lit_comp("end"),
    str_lit_comp("page_down"),
    str_lit_comp("up"),
    str_lit_comp("left"),
    str_lit_comp("down"),
    str_lit_comp("right"),
    str_lit_comp("ex0"),
    str_lit_comp("ex1"),
    str_lit_comp("ex2"),
    str_lit_comp("ex3"),
    str_lit_comp("ex4"),
    str_lit_comp("ex5"),
    str_lit_comp("ex6"),
    str_lit_comp("ex7"),
    str_lit_comp("ex8"),
    str_lit_comp("ex9"),
    str_lit_comp("ex10"),
    str_lit_comp("ex11"),
    str_lit_comp("ex12"),
    str_lit_comp("ex13"),
    str_lit_comp("ex14"),
    str_lit_comp("ex15"),
    str_lit_comp("ex16"),
    str_lit_comp("ex17"),
    str_lit_comp("ex18"),
    str_lit_comp("ex19"),
    str_lit_comp("ex20"),
    str_lit_comp("ex21"),
    str_lit_comp("ex22"),
    str_lit_comp("ex23"),
    str_lit_comp("ex24"),
    str_lit_comp("ex25"),
    str_lit_comp("ex26"),
    str_lit_comp("ex27"),
    str_lit_comp("ex28"),
    str_lit_comp("ex29"),
    str_lit_comp("num_lock"),
    str_lit_comp("numpad_slash"),
    str_lit_comp("numpad_star"),
    str_lit_comp("numpad_minus"),
    str_lit_comp("numpad_plus"),
    str_lit_comp("numpad_period"),
    str_lit_comp("numpad_0"),
    str_lit_comp("numpad_1"),
    str_lit_comp("numpad_2"),
    str_lit_comp("numpad_3"),
    str_lit_comp("numpad_4"),
    str_lit_comp("numpad_5"),
    str_lit_comp("numpad_6"),
    str_lit_comp("numpad_7"),
    str_lit_comp("numpad_8"),
    str_lit_comp("numpad_9"),
    str_lit_comp("left_mouse"),
    str_lit_comp("middle_mouse"),
    str_lit_comp("right_mouse"),
};

C_LINKAGE_END
